// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Details of a ghost commit created from a repository state.
 */
export type GhostCommit = { id: string, parent: string | null, };
