// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewSnapshotInfo = { snapshot_commit: string | null, branch: string | null, worktree_path: string | null, repo_root: string | null, };
