// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsage } from "./TokenUsage";

export type TokenUsageInfo = { total_token_usage: TokenUsage, last_token_usage: TokenUsage, requested_model?: string, latest_response_model?: string, model_context_window: number | null, };
