// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanItemArg } from "./PlanItemArg";

export type UpdatePlanArgs = { 
/**
 * Legacy field name used by existing clients.
 */
name: string | null, 
/**
 * Optional note used by newer clients; when provided it supersedes `name`.
 */
explanation: string | null, plan: Array<PlanItemArg>, };
